### ISSUE TITLE
Calling model_add_construction_set method for an ASHRAE 90.1-2004 on an empty model results in divide by 0 error

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#1343]
I found this when adding new spec tests to extension gem for space type mapping issue.
https://github.com/NREL/openstudio-extension-gem/issues/149#issuecomment-1188394239

When calling `model_add_construction_set` for `90.1-2004` it eventually calls `model_get_window_area_info` and if the model has no geometry, which is often case for space type and construction set wizard, it gets a divide by zero when checking windows.

Log shown below
```
 ZeroDivisionError:
   divided by 0
 # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb:2725:in `/'
 # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb:2725:in `model_get_window_area_info'
 # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/ashrae_90_1_2004.Model.rb:17:in `model_get_percent_of_surface_range'
 # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:2527:in `model_find_and_add_construction'
 # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:2708:in `model_add_construction_set'
```

**Comment by mdahlhausen** [comment]
Fixed with #1397
