### ISSUE TITLE
create_typical OpenStudio 3.8.0 test issues

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1745]
From tests in ComStock: 

- [x] NameError: undefined local variable or method `wkdy_op_hrs_start` for OpenstudioStandards::CreateTypical:Module
:/ruby/3.2.0/gems/openstudio-standards-0.6.0.rc2/lib/openstudio-standards/create_typical/create_typical.rb:147:in `create_typical_building_from_model' from https://github.com/NREL/ComStock/blob/04596fde2cedb085bd8aa506ae354f786b15efd6/resources/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb#L583

- [x] NoMethodError: undefined method `include?` for nil:NilClass
    :/ruby/3.2.0/gems/openstudio-standards-0.6.0.rc2/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:7399:in `model_add_hvac_system' from https://github.com/NREL/ComStock/blob/04596fde2cedb085bd8aa506ae354f786b15efd6/resources/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb#L122

**Comment by eringold** [comment]
Second one was actually a problem in ComStock, fixed there: https://github.com/NREL/ComStock/commit/119632576b92499fda908c77646a069d719d36df
