### ISSUE TITLE
cannot load such file -- zip

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#1859]
```
$ docker run -it --rm nrel/openstudio:3.9.0
```

Inside the docker:

```
$ gem install openstudio-standards
[...]
Installing ri documentation for openstudio-standards-0.7.0

$ irb
```

Inside irb

```
irb(main):001:0> require 'openstudio-standards'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- zip (LoadError)
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'                                                  
        from /usr/local/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.7.0/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:4:in `<class:NECB2011>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.7.0/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb:3:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.7.0/lib/openstudio-standards.rb:106:in `require_relative'                      
        from /usr/local/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.7.0/lib/openstudio-standards.rb:106:in `<module:OpenstudioStandards>'          
        from /usr/local/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.7.0/lib/openstudio-standards.rb:5:in `<top (required)>'                        
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'                                                 
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'                                       
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'                                                  
        from (irb):1:in `<main>'                                                                                                                       
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'                                                            
        from /usr/local/bin/irb:25:in `load'                                                                                                           
        from /usr/local/bin/irb:25:in `<main>'                                                                                                         
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- openstudio-standards (LoadError)    
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:25:in `load'
	from /usr/local/bin/irb:25:in `<main>'
```

`gem install zip` fixes it

**Comment by mdahlhausen** [comment]
It looks like the gem needs to be installed in the docker image directly; the openstudio-standards gemspec is insufficient. Will update when it is added there.

**Comment by mdahlhausen** [comment]
Fixed by adding the gem to the OpenStudio docker container [here](https://github.com/NREL/docker-openstudio/pull/201).
