### ISSUE TITLE
DOE Baseline errors with model where space type doesn't have standards space type or building type defined

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#516]
I'll add a test model into the measure repo for this after the 2.7.0 release tag. Here is error from datapoint.

```
"[09:53:16.234813 ERROR] undefined method `include?' for nil:NilClass
",
"	:/ruby/2.2.0/gems/openstudio-standards-0.2.6/lib/openstudio-standards/standards/Standards.Space.rb:1051:in `space_add_daylighting_controls'
",
"	:/ruby/2.2.0/gems/openstudio-standards-0.2.6/lib/openstudio-standards/standards/Standards.Model.rb:73:in `block in model_create_prm_baseline_building'
",
"	:/ruby/2.2.0/gems/openstudio-standards-0.2.6/lib/openstudio-standards/standards/Standards.Model.rb:72:in `each'
",
"	:/ruby/2.2.0/gems/openstudio-standards-0.2.6/lib/openstudio-standards/standards/Standards.Model.rb:72:in `model_create_prm_baseline_building'
",
```

**Comment by mdahlhausen** [comment]
Fixed previously, but more logging in #1473
